#!/bin/bash

freeze() {
  pip3 freeze >requirements.txt
}

create_venv() {
  python3 -m venv .venv
}

install_libraries() {
  pip3 install -r requirements.txt
}

create_kernel() {
  python3 -m ipykernel install --user --name=nb_text_mining
}

export_model() {
  echo "Please wait... generate buid/model-export.py"
  python3 build/model-export.py
}

preprocessing_data() {
  echo "Please wait... Step 1: Case Folding"
  python3 data/preprocessing/1-case-folding/case-folding.py

  echo "Please wait... Step 2: Cleaning"
  python3 data/preprocessing/2-cleaning/cleaning.py

  echo "Please wait... Step 3: Filtering"
  python3 data/preprocessing/3-filtering/filtering.py

  echo "Please wait... Step 4: Stemming"
  python3 data/preprocessing/4-stemming/stemming.py

  echo "Please wait... Step 5: Labeling"
  python3 data/preprocessing/5-labeling/labeling.py

  echo "...FINISH"
}

run_server() {
  streamlit run app/web-app.py
}

info() {
  echo "-h   --help"
  echo "-cv  --create-venv"
  echo "-ck  --create-kernel"
  echo "-p   --preprocessing : manage raw data"
  echo "-s   --streamlit     : running streamlit"
  echo "-e   --export        : export model py to pkl"
  echo "-f   --freeze        : export all libraries to txt"
  echo "-i   --install       : install all libraries"
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  info
elif [ "$1" = "-cv" ] || [ "$1" = "--create-venv" ]; then
  create_venv
elif [ "$1" = "-p" ] || [ "$1" = "--preprocessing" ]; then
  preprocessing_data
elif [ "$1" = "-ck" ] || [ "$1" = "--create-kernel" ]; then
  create_kernel
elif [ "$1" = "-e" ] || [ "$1" = "--export" ]; then
  export_model
elif [ "$1" = "-f" ] || [ "$1" = "--freeze" ]; then
  freeze
elif [ "$1" = "-i" ] || [ "$1" = "--install" ]; then
  install_libraries
elif [ "$1" = "-s" ] || [ "$1" = "--streamlit" ]; then
  run_server
else
  echo "Unknown option: $1"
  info
fi
